name: Continuous Integration

on:
  push:
    paths-ignore:
    - 'doc/**'
    - '**.md'
  pull_request:
  schedule:
  - cron: '0 0 * * TUE'
  workflow_dispatch:

env:
  CMAKE_C_COMPILER_LAUNCHER: ccache
  CMAKE_CXX_COMPILER_LAUNCHER: ccache

jobs:
  maybe_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{steps.skip_check.outputs.should_skip}}
    steps:
    - uses: fkirc/skip-duplicate-actions@v5
      id: skip_check
      with:
        cancel_others: 'true'

  build:
    name: build (${{matrix.system.os}}, ${{matrix.system.compiler.cc}})
    runs-on: ${{matrix.system.os}}
    needs: maybe_skip
    if: ${{needs.maybe_skip.outputs.should_skip != 'true'}}

    strategy:
      fail-fast: false
      matrix:
        system:
        - { os: ubuntu-22.04, compiler: { cc: gcc-11,   cxx: g++-11 } }
        # https://github.com/roboticslab-uc3m/questions-and-answers/issues/101
        - { os: ubuntu-22.04, compiler: { cc: clang-15, cxx: clang++-15 } }
        - { os: ubuntu-24.04, compiler: { cc: gcc-13,   cxx: g++-13 } }
        - { os: ubuntu-24.04, compiler: { cc: clang-18, cxx: clang++-18 } }
        experimental:
        - ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}

    steps:
    - name: Check out main project
      uses: actions/checkout@v4

    - name: Check out Orocos KDL
      uses: actions/checkout@v4
      with:
        repository: orocos/orocos_kinematics_dynamics
        path: .deps/kdl

    - name: Check out SWIG
      if: ${{matrix.system.os == 'ubuntu-24.04'}}
      uses: actions/checkout@v4
      with:
        repository: swig/swig
        ref: v4.2.1
        path: .deps/swig

    - name: Install dependencies via apt
      run: sudo apt-get install -qq ccache libeigen3-dev googletest

    - name: Set up Ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{matrix.system.os}}-${{matrix.system.compiler.cc}}

    - name: Set environment variables
      run: |
        echo "CC=${{matrix.system.compiler.cc}}" >> $GITHUB_ENV
        echo "CXX=${{matrix.system.compiler.cxx}}" >> $GITHUB_ENV

    - name: Build Orocos KDL
      run: |
        cmake -S .deps/kdl/orocos_kdl -B .deps/kdl/orocos_kdl/build
        cmake --build .deps/kdl/orocos_kdl/build
        sudo cmake --install .deps/kdl/orocos_kdl/build

    - name: Build SWIG
      if: ${{matrix.system.os == 'ubuntu-24.04'}}
      run: |
        cmake -S .deps/swig -B .deps/swig/build
        cmake --build .deps/swig/build
        sudo cmake --install .deps/swig/build
        sudo ln -s /usr/local/bin/swig /usr/local/bin/swig4.0 # shadows /usr/bin/swig4.0

    - name: Configure main project
      run: cmake -S . -B ./build -DCREATE_BINDINGS_PYTHON=ON -DENABLE_examples=ON

    - name: Compile main project
      run: cmake --build ./build

    - name: Install main project
      run: sudo cmake --install ./build && sudo ldconfig

    - name: Test main project
      working-directory: build
      run: ctest -V
